apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/git-commit-email: argocd-bot@example.com
    argocd-image-updater.argoproj.io/git-commit-user: argocd-bot
    argocd-image-updater.argoproj.io/image-list: yongmin01/musiot
    argocd-image-updater.argoproj.io/musiot.allow-tags: regexp:^sha-[0-9a-f]+$
    argocd-image-updater.argoproj.io/musiot.update-strategy: digest
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/musiot.kustomize.image-name: yongmin01/musiot
  name: musiot
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s
    repoURL: https://github.com/yongmin01/MUSIOT_FE.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
      prune: false
status:
  controllerNamespace: argocd
  health:
    lastTransitionTime: '2025-10-15T12:49:36Z'
    status: Healthy
  history:
    - deployStartedAt: '2025-10-14T16:46:21Z'
      deployedAt: '2025-10-14T16:46:21Z'
      id: 0
      initiatedBy:
        automated: true
      revision: a19bc7b046fb573a051dbf4ac6969800817f3b10
      source:
        path: k8s
        repoURL: https://github.com/yongmin01/MUSIOT_FE.git
        targetRevision: HEAD
    - deployStartedAt: '2025-10-15T06:53:02Z'
      deployedAt: '2025-10-15T06:53:02Z'
      id: 1
      initiatedBy:
        automated: true
      revision: a24195ae05cba62d61add85841ce3aa88bdd400f
      source:
        path: k8s
        repoURL: https://github.com/yongmin01/MUSIOT_FE.git
        targetRevision: HEAD
    - deployStartedAt: '2025-10-15T07:09:01Z'
      deployedAt: '2025-10-15T07:09:01Z'
      id: 2
      initiatedBy:
        automated: true
      revision: daff321ac4a1c230fcf15760238079ba888b5e87
      source:
        path: k8s
        repoURL: https://github.com/yongmin01/MUSIOT_FE.git
        targetRevision: HEAD
    - deployStartedAt: '2025-10-15T12:25:42Z'
      deployedAt: '2025-10-15T12:25:42Z'
      id: 3
      initiatedBy:
        automated: true
      revision: 8666e70fe881188fe3a6e08b7b635b9d61763dff
      source:
        path: k8s
        repoURL: https://github.com/yongmin01/MUSIOT_FE.git
        targetRevision: HEAD
    - deployStartedAt: '2025-10-15T12:49:36Z'
      deployedAt: '2025-10-15T12:49:36Z'
      id: 4
      initiatedBy:
        automated: true
      revision: da1325ae9c0dccd8ccbfe81f309ae66e2fbc4051
      source:
        path: k8s
        repoURL: https://github.com/yongmin01/MUSIOT_FE.git
        targetRevision: HEAD
  operationState:
    finishedAt: '2025-10-15T12:49:36Z'
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        automated: true
      retry:
        limit: 5
      sync:
        prune: true
        revision: da1325ae9c0dccd8ccbfe81f309ae66e2fbc4051
    phase: Succeeded
    startedAt: '2025-10-15T12:49:36Z'
    syncResult:
      resources:
        - group: networking.k8s.io
          hookPhase: Succeeded
          kind: Ingress
          message: pruned
          name: argocd-ingress
          namespace: argocd
          status: Pruned
          syncPhase: Sync
          version: v1
        - group: ''
          hookPhase: Running
          kind: Service
          message: service/musiot-service unchanged
          name: musiot-service
          namespace: default
          status: Synced
          syncPhase: Sync
          version: v1
        - group: apps
          hookPhase: Running
          images:
            - yongmin01/musiot:latest
          kind: Deployment
          message: deployment.apps/musiot-deployment unchanged
          name: musiot-deployment
          namespace: default
          status: Synced
          syncPhase: Sync
          version: v1
        - group: networking.k8s.io
          hookPhase: Running
          kind: Ingress
          message: ingress.networking.k8s.io/musiot-ingress unchanged
          name: musiot-ingress
          namespace: default
          status: Synced
          syncPhase: Sync
          version: v1
      revision: da1325ae9c0dccd8ccbfe81f309ae66e2fbc4051
      source:
        path: k8s
        repoURL: https://github.com/yongmin01/MUSIOT_FE.git
        targetRevision: HEAD
  reconciledAt: '2025-10-15T16:00:55Z'
  resourceHealthSource: appTree
  resources:
    - kind: Service
      name: musiot-service
      namespace: default
      status: Synced
      version: v1
    - group: apps
      kind: Deployment
      name: musiot-deployment
      namespace: default
      status: Synced
      version: v1
    - group: networking.k8s.io
      kind: Ingress
      name: musiot-ingress
      namespace: default
      status: Synced
      version: v1
  sourceHydrator: {}
  sourceType: Kustomize
  summary:
    externalURLs:
      - http://musiot.local/
    images:
      - yongmin01/musiot:latest
  sync:
    comparedTo:
      destination:
        namespace: default
        server: https://kubernetes.default.svc
      source:
        path: k8s
        repoURL: https://github.com/yongmin01/MUSIOT_FE.git
        targetRevision: HEAD
    revision: da1325ae9c0dccd8ccbfe81f309ae66e2fbc4051
    status: Synced
