apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/git-commit-email: argocd-bot@example.com
    argocd-image-updater.argoproj.io/git-commit-user: argocd-bot
    argocd-image-updater.argoproj.io/image-list: musiot=yongmin01/musiot
    argocd-image-updater.argoproj.io/musiot.allow-tags: regexp:^sha-[0-9a-f]+$
    argocd-image-updater.argoproj.io/musiot.update-strategy: newest-build
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/musiot.kustomize.image-name: yongmin01/musiot
    argocd-image-updater.argoproj.io/git-commit-message: 'build: automatic update of {{app}} [skip ci]'

  name: musiot
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s
    repoURL: https://github.com/yongmin01/MUSIOT_FE.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
      prune: false
